services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    image: starsoft-frontend-challenge:latest
    container_name: starsoft-frontend
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env.prod
    environment:
      - NODE_ENV=production
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    networks:
      - starsoft-network

networks:
  starsoft-network:
    driver: bridge